# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0a8d774af6e67901413be2e9e422b9ebf4fceb56071aad24829a530bd5f00569d5f026121b6a419cde66ac3404a7423ecf1ede86b23a8fba8e973b8c4e0a52a

test:
  secret_key_base: 97cb4be8c482faebbd25a61a411fade8ef46ab9287ea4ca7d7c48ad85f7ba8893a9c71854478216105fd5127c45985be4108f89fde3a74791cd142c638dfb283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
